using System.Collections.Generic;
using ZKWeb.Localize;
using ZKWebStandard.Extensions;
using ZKWebStandard.Ioc;

namespace ZKWeb.Plugins.Shopping.Order.src.Components.Translates {
	/// <summary>
	/// 韩语翻译
	/// </summary>
	[ExportMany, SingletonReuse]
	public class ko_KR : ITranslateProvider {
		private static HashSet<string> Codes = new HashSet<string>() { "ko-KR" };
		private static Dictionary<string, string> Translates = new Dictionary<string, string>()
		{
			{ "Order", "주문 용지" },
			{ "OrderManage", "주문 관리" },
			{ "Order management for ec site", "쇼핑몰 사이트는 순서 관리 기능을 이용" },
			{ "Buynow", "지금 주문" },
			{ "AddToCart", "장바구니에 추가" },
			{ "Cart", "카트" },
			{ "The product you are try to purchase does not exist.",
				"당신이 제품이 존재하지 않습니다 구입하려고" },
			{ "The product you are try to purchase does not purchasable.",
				"당신이 구입하려고하는 제품을 구매할하지 않습니다" },
			{ "Order count must larger than 0", "주문 횟수해야보다 큰 0" },
			{ "OrderSettings", "주문 설정" },
			{ "BuynowCartProductExpiresDays", "지금 주문 장바구니 제품 일 만료" },
			{ "NormalCartProductExpiresDays", "일반 장바구니 제품 일 만료" },
			{ "AutoConfirmOrderAfterDays", "일 후 자동 확인 주문" },
			{ "AllowAnonymousVisitorCreateOrder", "익명 방문자가 오더 생성 허용" },
			{ "Create order require user logged in", "순서는 사용자가 로그인을 필요로 만들기" },
			{ "ProductUnitPrice", "제품 단가" },
			{ "ProductTotalPrice", "제품 총 가격" },
			{ "LogisticsCost", "물류 비용" },
			{ "Create order contains multi currency is not supported",
				"성 순서는 다중 통화가 지원되지 않습니다 포함" },
			{ "Add product to cart success", "카트 성공에 제품 추가" },
			{ "Total products", "전체 제품" },
			{ "Product total price", "제품 총 가격" },
			{ "Close", "닫기" },
			{ "Checkout >>>", "점검 >>>" },
			{ "Order product unit price must not be negative", "주문 제품 단가가 음수가 아니어야합니다" },
			{ "Order cost must larger than 0", "주문 비용을해야보다 큰 0" },
			{ "Cart <em>[0]</em> products", "카트 <em>[0]</em>제품" },
			{ "<em>[0]</em> Products", "전부<em>[0]</em>개 제품" },
			{ "Total <em>[0]</em>", "전부<em>[0]</em>" },
			{ "Cart is empty", "빨리 쇼핑 카트 아직 상품 및 구입！" },
			{ "Recently add to cart", "최근 장바구니에 담기" },
			{ "Delete Successfully", "성공적으로 삭제" },
			{ "ShippingAddress", "배송 주소" },
			{ "Address/Name/Tel", "주소/이름/전화" },
			{ "ZipCode", "우편 번호" },
			{ "DetailedAddress", "주소" },
			{ "Fullname", "전체 이름" },
			{ "TelOrMobile", "전화/모바일" },
			{ "SubmitOrder", "주문을 제출" },
			{ "Calculating...", "계산하는..." },
			{ "Products total count: <em>0</em>", "항목의 총 수: <em>0</em>" },
			{ "Products total price: <em>0</em>", "상품 총 가격: <em>0</em>" },
			{ "Shipping Address:", "배송 주소:" },
			{ "Use new address", "새 주소" },
			{ "Manage shipping address", "배송 주소 관리" },
			{ "Check this will save or add shipping address",
				"기존 주소를 저장하거나 새 주소를 추가하려면 여기를 확인" },
			{ "Save shipping address", "저장 배송 주소" },
			{ "OrderComment", "주문 메시지" },
			{ "Logistics:", "물류 배송:" },
			{ "Logistics([0]):", "물류 배송([0]):" },
			{ "PaymentApi:", "지불 게이트웨이:" },
			{ "OrderTransaction", "주문 트랜잭션" },
			{ "Order Comment:", "주문 메시지:" },
			{ "Please select the products you want to purchase", "당신이 구입하려는 항목을 선택하세요" },
			{ "Selected logistics is not available for this seller", "판매자 선택된 스트림을 사용할 수 없다" },
			{ "Please select logistics", "물류를 선택" },
			{ "Please select payment api", "선택 결제 인터페이스" },
			{ "AutoCancelOrderAfterDays", "자동으로 비 지불 순서를 몇 일 취소" },
			{ "StockReductionMode", "재고 감소 모드" },
			{ "NoReduction", " 을 감소하지 않습니다" },
			{ "AfterCreateOrder", "당신이 주문을 만든 후" },
			{ "AfterOrderPaid", "성공적인 지불 후" },
			{ "Order contains product that not exist or deleted", "주문은 존재하지 않습니다 포함 또는 항목이 삭제 된" },
			{ "Insufficient stock of product [{0}]", "상품의 부족 [{0}] 재고" },
			{ "Order contains real products, please select a logistics", "주문은 실제 상품은 물류를 선택하십시오 포함" },
			{ "Please provide detailed address", "주소의 세부 사항을 제공하십시오" },
			{ "Please provide receiver name", "수취인의 이름을 입력하세요" },
			{ "Please provide receiver tel or mobile", "수취인 또는 휴대 전화를 입력하세요" },
			{ "To create order please login first", "주문을 만들기 로그인" },
			{ "Selected logistics is not allowed to use", "허용하지 않는 물류를 선택, 기타 물류를 선택하십시오" },
			{ "Selected payment api is not allowed to use",
				"지불 게이트웨이를 선택하고 사용할 수 없습니다, 다른 결제 인터페이스를 선택하십시오" },
			{ "MergedOrderTransaction", "조합 순서 거래" },
			{ "Order not found", "주문이 존재하지 않습니다" },
			{ "Unknow order state: [0]", "알 수없는 주문 상태: [0]" },
			{ "Order Checkout", "주문 결제" },
			{ "Order successfully created, please continue to pay", "결제를 성공적으로 만들어 주문" },
			{ "Merged transaction successfully created, please continue to pay",
				"통합 된 트랜잭션이 성공적으로 생성되었으므로 계속 지불하십시오" },
			{ "You have paid successful, please wait for seller delivery",
				"당신은 지불이 성공이 출하 판매자 기다려주십시오" },
			{ "You have paid successful, please check following orders",
				"당신은 지불이 성공해야 다음 주문을 확인" },
			{ "All goods shipped, please confirm order after receipt all goods",
				"판매자가 제공 한 물품 수령 후 영수증을 확인하시기 바랍니다" },
			{ "Order is successed, thank you for your patronage",
				"주문 트랜잭션은 당신의 후원에 감사 성공" },
			{ "Order is canceled", "주문 취소" },
			{ "Order is obsoleted", "사용되지 않는 주문" },
			{ "OrderSerial", "주문 번호" },
			{ "OrderAmount", "주문 금액" },
			{ "PaymentAmount", "결제 금액" },
			{ "Pay with [0]", "[0] 지불하는 데 사용합니다" },
			{ "Redirecting to order details page......", "세부 정보 페이지를 주문 리디렉션……" },
			{ "Redirecting to order list page......", "페이지로 이동 주문의 목록입니다……" },
			{ "RemarkFlags", "비고 배너" },
			{ "Serial/Remark", "번호 / 비고" },
			{ "Buyer", "구매자" },
			{ "Gray", "회색" },
			{ "Red", "빨간" },
			{ "Yellow", "황색" },
			{ "Green", "녹색" },
			{ "Blue", "푸른" },
			{ "Purple", "퍼플" },
			{ "OrderProducts", "제품 주문" },
			{ "Quantity", "양" },
			{ "ShippedQuantity", "출하 수량" },
			{ "ThisDeliveryQuantity", "선적의 수" },
			{ "Cost", "돈" },
			{ "TotalCost", "총 금액" },
			{ "OrderPricePart", "주문 가격의 일부" },
			{ "SellerOrder", "판매자가 주문" },
			{ "BuyerOrder", "구매자 주문" },
			{ "WaitingBuyerPay", "결제 대기 중" },
			{ "WaitingSellerDeliveryGoods", "배달을 위해 대기" },
			{ "WaitingBuyerConfirm", "배송" },
			{ "OrderSuccess", "무역 성공" },
			{ "OrderCancelled", "취소" },
			{ "OrderInvalid", "폐기" },
			{ "DeliveryRecords", "배송 기록" },
			{ "OrderRecords", "주문 내역" },
			{ "ReleatedTransactions", "특수 관계자 거래" },
			{ "OrderComments", "주문 메시지" },
			{ "Order Informations", "주문 정보" },
			{ "You're using secured paid, please confirm transaction on payment platform after received goods",
				"당신은 보안 트랜잭션을 사용하고, 지불 거래 플랫폼 제품의 영수증을 확인하시기 바랍니다" },
			{ "Buyer is using secured paid, please tell the buyer confirm transaction on payment platform after received goods",
				"구매자는 보안 트랜잭션을 사용하고, 상품 수령 후 거래에서 결제 플랫폼을 확인하기 위해 구매자를 알려 주시기 바랍니다" },
			{ "Releated transaction contains error: {0}", "관련 트랜잭션에 오류가 있습니다 : {0}" },
			{ "Copy shipping address to clipboard", "복사 배송 주소" },
			{ "BuyerComment", "구매자 피드백" },
			{ "SellerComment", "판매자 메시지" },
			{ "More", "더" },
			{ "OrderLogistics", "물류 및 유통" },
			{ "Order not payable because it's not waiting buyer pay",
				"상태는 지불의 순서를 기다리고되지 않고 결제를 지원하지 않기 때문에" },
			{ "Order not payable because no payable releated transactions",
				"더 주문 결제를 지원하지 않는 관련 거래를 지불하기 때문에" },
			{ "Order not cancellable because it's not waiting buyer pay",
				"상태 결제 순서를 기다리고 있지 않으므로 폐지를 지원하지" },
			{ "Order not cancellable because some releated transaction already paid",
				"트랜잭션이 지급되었을 때문에 폐지를 지원하지 않습니다" },
			{ "Order can't be confirmed because it's not waiting buyer confirm",
				"상태는 주문이 배송되지 않기 때문에, 영수증의 확인을 지원하지 않습니다" },
			{ "Order can't edit cost because it's not waiting buyer pay",
				"대신 지불 명령을 기다리고의 가격은 수정할 수 없습니다" },
			{ "Order can't edit cost because some releated transaction paid or realized",
				"관련 당사자 거래는 지불했거나 지불 플랫폼에 최선을 다하고, 가격은 수정할 수 없습니다" },
			{ "Order can't edit shipping address because it's not waiting buyer pay or waiting seller send goods",
				"대신 지불하기 위해 대기 또는 전달을 위해 대기 중, 배달 주소는 편집 할 수 없습니다" },
			{ "Order can't send goods because it's not waiting seller send goods", "订单不是等待发货，不能进行发货" },
			{ "Order already invalid", "주문 상태가 취소되었습니다" },
			{ "Order already cancelled", "주문 상태가 취소되었습니다" },
			{ "Order can't be paid because it's not waiting buyer pay",
				"대신 지불하기 위해 기다리는 세트를 지급 할 수 없다" },
			{ "Order can't be paid because not all releated transaction paid",
				"순서 무급 거래 관련 당사자 거래, 지불하지"},
			{ "Order can't be shipped because not waiting seller send goods",
				"대신 배송 주문을 기다리는, 그것은에 배송 할 수 없습니다" },
			{ "Order can't be shipped because not all goods shipped",
				"주문은 제품의 모든 출하량은 배송 할 수 없습니다하지 않은" },
			{ "Order can't be success because not waiting buyer confirm",
				"주문은 제공되지 성공적인 거래로 설정할 수 없습니다" },
			{ "No payable transaction releated to this order", "어떤 주문 트랜잭션을 지불 할 수 있습니다" },
			{ "PayNow", "즉시 결제" },
			{ "CancelOrder", "주문 취소" },
			{ "ConfirmOrder", "접수 확인" },
			{ "EditCost", "편집 가격" },
			{ "EditShippingAddress", "주소 편집" },
			{ "DeliveryGoods", "배달" },
			{ "ConfirmInsteadOfBuyer", "영수증의 확인" },
			{ "SetInvalid", "잘못된" },
			{ "OrderState", "주문 상태" },
			{ "OrderActions", "순서 작업" },
			{ "OriginalTotalCost", "원래의 총량" },
			{ "DeliverySerial", "송장 번호" },
			{ "LogisticsSerial", "하나의 숫자를 표현" },
			{ "DeliveryOperator", "위탁자" },
			{ "DeliveryTime", "배달 시간" },
			{ "View Transaction", "보기 거래" },
			{ "View Delivery", "보기 송장" },
			{ "To delete product please change the quantity to zero, and check transaction amount after modification",
				"항목 번호를 0으로 설정, 삭제, 거래 금액을 확인한 후 가격을 수정 바랍니다" },
			{ "Order total cost", "총 가격 주문" },
			{ "Order not exist", "주문이 존재하지 않습니다" },
			{ "Order product not exist", "주문 상품이 존재하지 않는다" },
			{ "Can't delete all products in the order", "당신은 순서에있는 모든 항목을 삭제할 수 없습니다" },
			{ "Amount changed by edit order cost, previous value is {0}", "의 값 전에, 주문 가격이 리드의 양을 변경 변경 {0}" },
			{ "Order total cost changed, previous value is {0}", "주문의 총 가격의 이전 값을 변경 {0}" },
			{ "ManuallyEditPrice", "수동으로 가격을 변경" },
			{ "Order shipping address changed, previous value is {0}", "주소를 발송 주문의 이전 값을 변경 {0}" },
			{ "Child transactions amount changed by edit order cost, this merge transaction should be aborted",
				"양이 자궁 경부 변화를 야기 주문 거래 금액을 수정, 합병은 중단되어야한다" },
			{ "Child transaction {0} process waiting paying standalone, this merge transaction should be aborted",
				"하위 트랜잭션 ({0}) 만 지불 처리 기다립니다,이 합병이 종료되어야한다" },
			{ "Child transaction {0} process secured paid standalone, this merge transaction should be aborted",
				"하위 트랜잭션 ({0}) 별도 보안 지불 거래를 처리되었습니다 합병이 종료되어야한다" },
			{ "Child transaction {0} process success standalone, this merge transaction should be aborted",
				"처리 된 서브 트랜잭션 ({0}) 별도로 트랜잭션이 성공적으로 합병이 종료되어야한다" },
			{ "Child transaction {0} aborted, this merge transaction should be aborted too",
				"하위 트랜잭션 ({0}) 일시 중지,이 합병은 중단되어야한다" },
			{ "Order secured paid from transaction, serial is {0}", "결제 거래 일련 번호를 완료하기 위해 보안 트랜잭션에 의해 주문은 {0}" },
			{ "Order is paid", "결제 주문" },
			{ "Can't process order paid, reason is {0}", "결제 주문 때문에 처리 할 수없는 {0}" },
			{ "All goods under order is shipped", "모든 주문 상품을 배송됩니다" },
			{ "Can't process order shipped, reason is {0}", "발송 한 명령을 처리 할 수 있으며, 그 이유는 {0}" },
			{ "Order is successed", "성공적인 거래 주문" },
			{ "Can't process order successed, reason is {0}", "주문은 트랜잭션이 성공적으로 처리 할 수 있으며, 그 이유는 {0}" },
			{ "Order paid from transaction, serial is {0}", "보통의 지불 거래에 의해 주문이 완료, 거래 일련 번호는 {0}입니다" },
			{ "Order confirmed from payment platform after secured paid, serial is {0}",
				"고정 거래를 통해 지불 주문은 거래 플랫폼에 영수증을 확인했습니다, 거래 일련 번호는 {0}입니다" },
			{ "Merged Order Checkout", "주문 통합 결제" },
			{ "Back to order list", "다시 주문 목록" },
			{ "Order Serial: {0}", "주문 번호 : {0}" },
			{ "Add comment here then click submit", "여기에 메시지를 추가하고 제출 버튼을 클릭합니다" },
			{ "Reason can't be empty", "이유는 비워 둘 수 없습니다" },
			{ "Order become invalid, reason is {0}", "주문이로 인해 취소되었습니다 {0}" },
			{ "Can't set order invalid, reason is {0}", "주문이 취소 될 수 없기 때문에 {0}" },
			{ "SetInvalidReason", "사용되지 않는 이유" },
			{ "The reason of set order invalid, must provide", "이유의 순서를 따로 설정, 필수" },
			{ "Set order invalid failed, please check order records", "주문 내역을 확인, 순서가 실패 따로 설정" },
			{ "Set order invalid success", "주문이 취소" },
			{ "Order cancelled, reason is {0}", "주문이로 인해 취소되었습니다 {0}" },
			{ "Can't cancel order, reason is {0}", "주문은 때문에 취소 할 수 없습니다 {0}" },
			{ "CancelReason", "취소 이유" },
			{ "The reason of cancel order, must provide", "이유는 주문을 취소 필수" },
			{ "Cancel order failed, please check order records", "주문 내역을 확인, 순서가 실패 취소" },
			{ "Cancel order success", "주문이 취소" },
			{ "Can't delivery product that not exists in order", "당신은 제공된 상품을 주문할 수 없습니다" },
			{ "Invalid delivery count", "출하량의 잘못된 번호" },
			{ "Delivery count can't be larger than unshipped count", "선적의 수보다 더 배달 수량 없음" },
			{ "No products to be delivery", "우리는 상품을 제공 할 필요가 없습니다" },
			{ "The shipping address is \"{0}\", and buyer want to use logistics \"{1}\"",
				"배송 주소는 \"{0}\", 구매자가 물류를 사용하려면 \"{1}\"" },
			{ "Order only contains virtual products, if you have something to buyer please use comment",
				"주문은 당신이 메시지를 사용하여 구매자에게 무엇이있는 경우에만 가상 상품을 포함" },
			{ "Please provide logistics serial (invoice no)", "물류 번호를 제공 (단일 숫자를 표현하는)하시기 바랍니다" },
			{ "Buyer confirm all goods shipped, 순서가 성공해야한다.",
				"구매자는 영수증, 주문 거래의 성공을 확인한다" },
			{ "Seller confirm order insetead of buyer, order should be success",
				"대신 백그라운드에서 구매자의 판매자가 영수증을 확인, 주문 거래 성공" },
			{ "Can't confirm order, reason is {0}", "영수증을 확인 할 수 없습니다 이유는 {0}" },
			{ "Thank you! Before you confirm receipt", "후원자 감사합니다! 접수 확인하기 전에, 제발" },
			{ "Make sure you have received all the goods", "모든 물건을 받았는지 확인" },
			{ "Confirm receipt of the goods in good condition and meet your requirements",
				"상태가 좋은 상품 수령을 인정하고 요구 사항을 충족" },
			{ "If you are using a secured transaction payment, you will also need to go to the payment platform (such as Alipay) to confirm receipt",
				"당신은 보안 지불 거래를 사용하는 경우, 당신은 또한 결제 플랫폼의 수신 (예: Paypal의 등) 확인해야" },
			{ "Thank you for your presence, welcome to buy our products again!",
				"다시 우리의 제품을 구입에 오신 것을 환영합니다, 여러분의 방문에 감사드립니다!" },
			{ "You are trying to confirm the goods receipt instead of the buyer, please confirm before submitting",
				"당신은 영수증을 확인하기 위해 구매자를 교체하려고, 제출하기 전에 확인하시기 바랍니다" },
			{ "Does the buyer not acknowledge receipt within the specified time?",
				"지정된 기간 내에 수신을 확인 할 구매자가 없다면?" },
			{ "You can also enable automatically confirm receipt feature form the order settings",
				"또한 주문 설정 기능의 영수증의 자동 확인을 활성화 할 수 있습니다" },
			{ "Confirm order failed, please check order records",
				"주문 내역 확인, 영수증을 확인하지 않으면" },
			{ "Confirm order success", "영수증의 성공을 확인" },
			{ "Auto confirm order after {0} days", "아직 {0} 일이 영수증을 확인 후, 자동으로 영수증을 확인" },
			{ "Auto cancel order after {0} days unpaid", "{0} 일 무급 유지 한 후, 주문이 자동으로 취소됩니다" },
			{ "MergePayment", "결합 된 유료" },
			{ "Please select orders to merge payment", "결제 주문 병합해야 선택하세요" },
			{ "Sure to merge following order's payment?", "다음 주문 결제 통합 확인？" },
			{ "Some order not exists", "존재하지 않는 순서의 일부" },
			{ "Merge payment required atleast 2 orders", "결합 지급은 적어도 두 개의 주문을 요구" },
			{ "Some order is not payable", "일부 주문은 지불 할 수" },
			{ "New merged transaction has created, this merge transaction should be aborted",
				"새로운 합병을 만든, 기존의 합병이 종료되어야한다" },
			{ "CartPage", "쇼핑 카트 페이지" },
			{ "CartContents", "카트보기" },
			{ "MiniCartMenu", "미니 카트 메뉴" },
			{ "ProductPurchaseButtons", "상품 구매 버튼" }
		};

		public bool CanTranslate(string code) {
			return Codes.Contains(code);
		}

		public string Translate(string text) {
			return Translates.GetOrDefault(text);
		}
	}
}
