using System.Collections.Generic;
using ZKWeb.Localize;
using ZKWebStandard.Extensions;
using ZKWebStandard.Ioc;

namespace ZKWeb.Plugins.Shopping.Order.src.Components.Translates {
	/// <summary>
	/// 繁体中文翻译
	/// </summary>
	[ExportMany, SingletonReuse]
	public class zh_TW : ITranslateProvider {
		private static HashSet<string> Codes = new HashSet<string>() { "zh-TW" };
		private static Dictionary<string, string> Translates = new Dictionary<string, string>()
		{
			{ "Order", "訂單" },
			{ "OrderManage", "訂單管理" },
			{ "Order management for ec site", "商城使用的訂單管理功能" },
			{ "Buynow", "立刻購買" },
			{ "AddToCart", "加入購物車" },
			{ "Cart", "購物車" },
			{ "The product you are try to purchase does not exist.", "您嘗試購買的商品不存在" },
			{ "The product you are try to purchase does not purchasable.", "您嘗試購買的商品目前不允許購買" },
			{ "Order count must larger than 0", "訂購數量必須大於0" },
			{ "OrderSettings", "訂單設置" },
			{ "BuynowCartProductExpiresDays", "立刻購買的購物車商品的過期天數" },
			{ "NormalCartProductExpiresDays", "壹般的購物車商品的過期天數" },
			{ "AutoConfirmOrderAfterDays", "自動確認收貨天數" },
			{ "AllowAnonymousVisitorCreateOrder", "允許非會員下單" },
			{ "Create order require user logged in", "創建訂單需要用戶登錄" },
			{ "ProductUnitPrice", "商品單價" },
			{ "ProductTotalPrice", "商品總價" },
			{ "LogisticsCost", "運費" },
			{ "Create order contains multi currency is not supported", "不支持創建包含多種貨幣的訂單" },
			{ "Add product to cart success", "成功添加商品到購物車" },
			{ "Total products", "共有商品" },
			{ "Product total price", "商品總價" },
			{ "Close", "關閉" },
			{ "Checkout >>>", "去結算 >>>" },
			{ "Order product unit price must not be negative", "訂單商品的單價必須大於或等於0" },
			{ "Order cost must larger than 0", "訂單總價必須大於0" },
			{ "Cart <em>[0]</em> products", "購物車<em>[0]</em>件" },
			{ "<em>[0]</em> Products", "共<em>[0]</em>件商品" },
			{ "Total <em>[0]</em>", "共<em>[0]</em>" },
			{ "Cart is empty", "購物車中還沒有商品，趕緊選購吧！" },
			{ "Recently add to cart", "最近加入購物車" },
			{ "Delete Successfully", "刪除成功" },
			{ "ShippingAddress", "收貨地址" },
			{ "Address/Name/Tel", "地址/姓名/電話" },
			{ "ZipCode", "郵政編碼" },
			{ "DetailedAddress", "詳細地址" },
			{ "Fullname", "姓名" },
			{ "TelOrMobile", "電話/手機" },
			{ "SubmitOrder", "提交訂單" },
			{ "Calculating...", "計算中..." },
			{ "Products total count: <em>0</em>", "商品總數量: <em>0</em>" },
			{ "Products total price: <em>0</em>", "商品總價格: <em>0</em>" },
			{ "Shipping Address:", "收貨地址:" },
			{ "Use new address", "使用新地址" },
			{ "Manage shipping address", "管理收貨地址" },
			{ "Check this will save or add shipping address", "勾選這裏可以保存現有地址或添加新的地址" },
			{ "Save shipping address", "保存收貨地址" },
			{ "OrderComment", "訂單留言" },
			{ "Logistics:", "物流配送:" },
			{ "Logistics([0]):", "物流配送([0]):" },
			{ "PaymentApi:", "支付接口:" },
			{ "OrderTransaction", "訂單交易" },
			{ "Order Comment:", "訂單留言:" },
			{ "Please select the products you want to purchase", "請選擇您想要購買的商品" },
			{ "Selected logistics is not available for this seller", "該賣家不可使用選擇的物流" },
			{ "Please select logistics", "請選擇物流" },
			{ "Please select payment api", "請選擇支付接口" },
			{ "AutoCancelOrderAfterDays", "自動取消未付款訂單天數" },
			{ "StockReductionMode", "庫存減少模式" },
			{ "NoReduction", "不減少" },
			{ "AfterCreateOrder", "創建訂單後" },
			{ "AfterOrderPaid", "支付成功後" },
			{ "Order contains product that not exist or deleted", "訂單包含不存在或已刪除的商品" },
			{ "Insufficient stock of product [{0}]", "商品[{0}]的庫存不足" },
			{ "Order contains real products, please select a logistics", "訂單包含實體商品，請選擇壹個物流" },
			{ "Please provide detailed address", "請提供詳細的地址" },
			{ "Please provide receiver name", "請提供收貨人姓名" },
			{ "Please provide receiver tel or mobile", "請提供收貨人電話或手機" },
			{ "To create order please login first", "請先登錄再創建訂單" },
			{ "Selected logistics is not allowed to use", "選擇的物流並不允許使用，請選擇其他物流" },
			{ "Selected payment api is not allowed to use", "選擇的支付接口並不允許使用，請選擇其他支付接口" },
			{ "MergedOrderTransaction", "合並訂單交易" },
			{ "Order not found", "訂單不存在" },
			{ "Unknow order state: [0]", "未知的訂單狀態: [0]" },
			{ "Order Checkout", "訂單結算" },
			{ "Order successfully created, please continue to pay", "訂單創建成功，請付款" },
			{ "Merged transaction successfully created, please continue to pay", "合並交易創建成功，請付款" },
			{ "You have paid successful, please wait for seller delivery", "您已付款成功，請等待賣家發貨" },
			{ "You have paid successful, please check following orders", "您已付款成功，請查看以下訂單" },
			{ "All goods shipped, please confirm order after receipt all goods", "賣家已發貨，請在收到貨物後確認收貨" },
			{ "Order is successed, thank you for your patronage", "訂單交易成功，感謝您的惠顧" },
			{ "Order is canceled", "訂單已取消" },
			{ "Order is obsoleted", "訂單已作廢" },
			{ "OrderSerial", "訂單編號" },
			{ "OrderAmount", "訂單金額" },
			{ "PaymentAmount", "支付金額" },
			{ "Pay with [0]", "使用[0]支付" },
			{ "Redirecting to order details page......", "正在跳轉到訂單詳情頁……" },
			{ "Redirecting to order list page......", "正在跳轉到訂單列表頁……" },
			{ "RemarkFlags", "備註旗幟" },
			{ "Serial/Remark", "編號/備註" },
			{ "Buyer", "買家" },
			{ "Gray", "灰色" },
			{ "Red", "紅色" },
			{ "Yellow", "黃色" },
			{ "Green", "綠色" },
			{ "Blue", "藍色" },
			{ "Purple", "紫色" },
			{ "OrderProducts", "訂單商品" },
			{ "Quantity", "數量" },
			{ "ShippedQuantity", "已發貨數量" },
			{ "ThisDeliveryQuantity", "本次發貨數量" },
			{ "Cost", "金額" },
			{ "TotalCost", "總金額" },
			{ "OrderPricePart", "訂單價格組成部分" },
			{ "SellerOrder", "賣家訂單" },
			{ "BuyerOrder", "買家訂單" },
			{ "WaitingBuyerPay", "等待付款" },
			{ "WaitingSellerDeliveryGoods", "等待發貨" },
			{ "WaitingBuyerConfirm", "已發貨" },
			{ "OrderSuccess", "交易成功" },
			{ "OrderCancelled", "已取消" },
			{ "OrderInvalid", "已作廢" },
			{ "DeliveryRecords", "發貨記錄" },
			{ "OrderRecords", "訂單記錄" },
			{ "ReleatedTransactions", "關聯交易" },
			{ "OrderComments", "訂單留言" },
			{ "Order Informations", "訂單信息" },
			{ "You're using secured paid, please confirm transaction on payment platform after received goods",
				"您正在使用擔保交易，請在收到貨物後到支付平臺上確認交易" },
			{ "Buyer is using secured paid, please tell the buyer confirm transaction on payment platform after received goods",
				"買家正在使用擔保交易，請通知買家在收到貨物後到支付平臺上確認交易" },
			{ "Releated transaction contains error: {0}", "關聯交易包含錯誤: {0}" },
			{ "Copy shipping address to clipboard", "復制收貨地址" },
			{ "BuyerComment", "買家留言" },
			{ "SellerComment", "賣家留言" },
			{ "More", "更多" },
			{ "OrderLogistics", "物流配送" },
			{ "Order not payable because it's not waiting buyer pay",
				"因為訂單狀態不是等待付款，不支持付款" },
			{ "Order not payable because no payable releated transactions",
				"因為訂單沒有可支付的關聯交易，不支持付款" },
			{ "Order not cancellable because it's not waiting buyer pay",
				"因為訂單狀態不是等待付款，不支持取消" },
			{ "Order not cancellable because some releated transaction already paid",
				"因為關聯交易已支付，不支持取消" },
			{ "Order can't be confirmed because it's not waiting buyer confirm",
				"因為訂單狀態不是已發貨，不支持確認收貨" },
			{ "Order can't edit cost because it's not waiting buyer pay",
				"訂單不是等待付款，不能修改價格" },
			{ "Order can't edit cost because some releated transaction paid or realized",
				"關聯交易已支付或提交到支付平臺，不能修改價格" },
			{ "Order can't edit shipping address because it's not waiting buyer pay or waiting seller send goods",
				"訂單不是等待付款或等待發貨，不能編輯收貨地址" },
			{ "Order can't send goods because it's not waiting seller send goods", "訂單不是等待發貨，不能進行發貨" },
			{ "Order already invalid", "訂單已經是作廢狀態" },
			{ "Order already cancelled", "訂單已經是取消狀態" },
			{ "Order can't be paid because it's not waiting buyer pay",
				"訂單不是等待付款，不能設為已付款" },
			{ "Order can't be paid because not all releated transaction paid",
				"訂單的關聯交易中有未付款的交易，不能設為已付款"},
			{ "Order can't be shipped because not waiting seller send goods",
				"訂單不是等待發貨，不能設為已發貨" },
			{ "Order can't be shipped because not all goods shipped",
				"訂單中有未全部發貨的商品，不能設為已發貨" },
			{ "Order can't be success because not waiting buyer confirm",
				"訂單不是已發貨，不能設為交易成功" },
			{ "No payable transaction releated to this order", "沒有可以支付的訂單交易" },
			{ "PayNow", "立刻付款" },
			{ "CancelOrder", "取消訂單" },
			{ "ConfirmOrder", "確認收貨" },
			{ "EditCost", "編輯價格" },
			{ "EditShippingAddress", "編輯地址" },
			{ "DeliveryGoods", "發貨" },
			{ "ConfirmInsteadOfBuyer", "代確認收貨" },
			{ "SetInvalid", "作廢" },
			{ "OrderState", "訂單狀態" },
			{ "OrderActions", "訂單操作" },
			{ "OriginalTotalCost", "原始總金額" },
			{ "DeliverySerial", "發貨單編號" },
			{ "LogisticsSerial", "快遞單編號" },
			{ "DeliveryOperator", "發貨人" },
			{ "DeliveryTime", "發貨時間" },
			{ "View Transaction", "查看交易" },
			{ "View Delivery", "查看發貨單" },
			{ "To delete product please change the quantity to zero, and check transaction amount after modification",
				"刪除商品請把數量設為0，並且在修改價格後檢查交易的金額" },
			{ "Order total cost", "訂單總價" },
			{ "Order not exist", "訂單不存在" },
			{ "Order product not exist", "訂單商品不存在" },
			{ "Can't delete all products in the order", "不能刪除訂單中的所有商品" },
			{ "Amount changed by edit order cost, previous value is {0}", "修改訂單價格導致金額改變，前值是{0}" },
			{ "Order total cost changed, previous value is {0}", "訂單總價已改變，前值是{0}" },
			{ "ManuallyEditPrice", "手動改價" },
			{ "Order shipping address changed, previous value is {0}", "訂單收貨地址已改變，前值是{0}" },
			{ "Child transactions amount changed by edit order cost, this merge transaction should be aborted",
				"修改訂單金額導致子交易金額改變，這個合並交易應當被中止" },
			{ "Child transaction {0} process waiting paying standalone, this merge transaction should be aborted",
				"子交易({0})單獨處理等待付款，這個合並交易應當被終止" },
			{ "Child transaction {0} process secured paid standalone, this merge transaction should be aborted",
				"子交易({0})單獨處理擔保交易已付款，這個合並交易應當被終止" },
			{ "Child transaction {0} process success standalone, this merge transaction should be aborted",
				"子交易({0})單獨處理交易成功，這個合並交易應當被終止" },
			{ "Child transaction {0} aborted, this merge transaction should be aborted too",
				"子交易({0})被中止，這個合並交易也應當被中止" },
			{ "Order secured paid from transaction, serial is {0}", "訂單通過擔保交易支付完成，交易序列號是{0}" },
			{ "Order is paid", "訂單已付款" },
			{ "Can't process order paid, reason is {0}", "不能處理訂單已付款，原因是{0}" },
			{ "All goods under order is shipped", "訂單中的所有商品均已發貨" },
			{ "Can't process order shipped, reason is {0}", "不能處理訂單已發貨，原因是{0}" },
			{ "Order is successed", "訂單交易成功" },
			{ "Can't process order successed, reason is {0}", "不能處理訂單交易成功，原因是{0}" },
			{ "Order paid from transaction, serial is {0}", "訂單通過普通交易支付完成，交易序列號是{0}" },
			{ "Order confirmed from payment platform after secured paid, serial is {0}",
				"通過擔保交易支付的訂單在交易平臺上已確認收貨，交易序列號是{0}" },
			{ "Merged Order Checkout", "訂單合並結算" },
			{ "Back to order list", "返回訂單列表" },
			{ "Order Serial: {0}", "訂單編號: {0}" },
			{ "Add comment here then click submit", "添加留言到這裏並點擊提交按鈕" },
			{ "Reason can't be empty", "原因不能為空" },
			{ "Order become invalid, reason is {0}", "訂單已作廢，原因是{0}" },
			{ "Can't set order invalid, reason is {0}", "不能作廢訂單，原因是{0}" },
			{ "SetInvalidReason", "作廢原因" },
			{ "The reason of set order invalid, must provide", "作廢訂單的原因，必填" },
			{ "Set order invalid failed, please check order records", "作廢訂單失敗，請檢查訂單記錄" },
			{ "Set order invalid success", "作廢訂單成功" },
			{ "Order cancelled, reason is {0}", "訂單已取消，原因是{0}" },
			{ "Can't cancel order, reason is {0}", "不能取消訂單，原因是{0}" },
			{ "CancelReason", "取消原因" },
			{ "The reason of cancel order, must provide", "取消訂單的原因，必填" },
			{ "Cancel order failed, please check order records", "取消訂單失敗，請檢查訂單記錄" },
			{ "Cancel order success", "取消訂單成功" },
			{ "Can't delivery product that not exists in order", "不能對不在訂單中的商品進行發貨" },
			{ "Invalid delivery count", "發貨數量不正確" },
			{ "Delivery count can't be larger than unshipped count", "發貨數量大於未發貨數量" },
			{ "No products to be delivery", "沒有要發貨的商品" },
			{ "The shipping address is \"{0}\", and buyer want to use logistics \"{1}\"",
				"收貨地址是\"{0}\"，且買家希望使用物流\"{1}\"" },
			{ "Order only contains virtual products, if you have something to buyer please use comment",
				"訂單僅包含虛擬商品，如果您有什麽需要給買家請使用留言" },
			{ "Please provide logistics serial (invoice no)", "請提供物流編號(快遞單編號)" },
			{ "Buyer confirm all goods shipped, order should be success",
				"買家已確認收貨，訂單交易成功" },
			{ "Seller confirm order insetead of buyer, order should be success",
				"賣家在後臺代替買家確認收貨，訂單交易成功" },
			{ "Can't confirm order, reason is {0}", "不能確認收貨，原因是{0}" },
			{ "Thank you! Before you confirm receipt", "謝謝惠顧！在確認收貨之前請先" },
			{ "Make sure you have received all the goods", "確認您已收到所有的商品" },
			{ "Confirm receipt of the goods in good condition and meet your requirements",
				"確認收到的商品完好無損並滿足您的要求" },
			{ "If you are using a secured transaction payment, you will also need to go to the payment platform (such as Alipay) to confirm receipt",
				"如果您使用的是擔保交易支付，您還需要到支付平臺(例如支付寶)上確認收貨" },
			{ "Thank you for your presence, welcome to buy our products again!",
				"感謝您的光臨，歡迎再次購買我們的商品！" },
			{ "You are trying to confirm the goods receipt instead of the buyer, please confirm before submitting",
				"您正在嘗試代替買家確認收貨，請在提交前先確認" },
			{ "Does the buyer not acknowledge receipt within the specified time?",
				"買家是否在規定的時間內沒有確認收貨？" },
			{ "You can also enable automatically confirm receipt feature form the order settings",
				"您還可以在訂單設置中啟用自動確認收貨的功能" },
			{ "Confirm order failed, please check order records",
				"確認收貨失敗，請檢查訂單記錄" },
			{ "Confirm order success", "確認收貨成功" },
			{ "Auto confirm order after {0} days", "在經過{0}天後仍未確認收貨，自動確認收貨" },
			{ "Auto cancel order after {0} days unpaid", "在經過{0}天後仍未付款，自動取消訂單" },
			{ "MergePayment", "合並支付" },
			{ "Please select orders to merge payment", "請選擇需要合並支付的訂單" },
			{ "Sure to merge following order's payment?", "確認合並以下訂單的支付？" },
			{ "Some order not exists", "部分訂單不存在" },
			{ "Merge payment required atleast 2 orders", "合並支付需要至少兩個訂單" },
			{ "Some order is not payable", "部分訂單不可支付" },
			{ "New merged transaction has created, this merge transaction should be aborted",
				"已創建新的合並交易，舊的合並交易應該被終止" },
			{ "CartPage", "購物車頁" },
			{ "CartContents", "購物車內容" },
			{ "MiniCartMenu", "迷妳購物車菜單" },
			{ "ProductPurchaseButtons", "商品購買按鈕" }
		};

		public bool CanTranslate(string code) {
			return Codes.Contains(code);
		}

		public string Translate(string text) {
			return Translates.GetOrDefault(text);
		}
	}
}
